version: '3'

services:
  authentication-service:
    build: ./authentication-service
    ports:
      - "3000:3000"
    volumes:
      - ./authentication-service:/app
    command: npm start

  authors-service:
    build: ./authors-service
    ports:
      - "4000:4000"
    volumes:
      - ./authors-service:/app
      - authors-db:/var/lib/authors-service
    command: npm start

  books-service:
    build: ./books-service
    ports:
      - "5000:5000"
    volumes:
      - ./books-service:/app
      - books-db:/var/lib/books-service
    command: npm start

  categories-service:
    build: ./categories-service
    ports:
      - "6000:6000"
    volumes:
      - ./categories-service:/app
      - categories-db:/var/lib/categories-service
    command: npm start

  reviews-service:
    build: ./reviews-service
    ports:
      - "7000:7000"
    volumes:
      - ./reviews-service:/app
      - reviews-db:/var/lib/reviews-service
    command: npm start

  users-service:
    build: ./users-service
    ports:
      - "8000:8000"
    volumes:
      - ./users-service:/app
      - users-db:/var/lib/users-service
    command: npm start

  event-bus-service:
    build: ./event-bus
    volumes:
      - ./event-bus:/app
    command: npm start
    ports:
      - 9000:9000

volumes:
  authors-db:
  books-db:
  categories-db:
  reviews-db:
  users-db:
